# Generated by Django 5.2 on 2025-04-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=10, unique=True)),
                ('course_description', models.TextField()),
                ('course_credits', models.IntegerField()),
                ('course_prerequisites', models.TextField()),
                ('course_semester', models.CharField(max_length=10)),
                ('course_image_url', models.URLField(blank=True, null=True)),
                ('professor_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('hints', models.TextField()),
                ('extra_resources', models.TextField()),
                ('sylabus_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
